export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const DISABLED_BUTTON = 'DISABLED_BUTTON'
export const ENABLED_BUTTON = 'ENABLED_BUTTON'

export const GET_USERS = 'GET_USERS'
export const GET_MORE_USERS = 'GET_MORE_USERS'
export const RESET_USERS = 'RESET_USERS'
export const GET_USER = 'GET_USER'
export const GET_REPOS = 'GET_REPOS'
export const SET_LOADING = 'SET_LOADING'
